### ISSUE TITLE
Сервер

### ISSUE THREAD

**Issue by DamirZaripov16** [DamirZaripov16/readLater#1]
@coursar Ильназ, можете объяснить каким образом подвязать сервер к приложению?
-Т.е. нужно создать три файла: http.js, rest.js и requests.http? 
- request.http и http.js и rest.js можно сразу полностью скопировать?
- куда следует импортировать элементы сервера в DOM'ном файле (app.js)? Только в event'ы?

**Comment by coursar** [comment]
Для сервера - только rest.js. http.js - это обращение к серверу из браузера.
