### ISSUE TITLE
Общие вопросы

### ISSUE THREAD

**Issue by DamirZaripov16** [DamirZaripov16/readLater#2]
@coursar Ильназ, подскажите, пожалуйста, с примерами:
 - нужно через инпуты вносить произвольные данные или только те, которые мы предопределим в lib.js? (как в KFC);
 - как запретить добавлять в лист ссылку, если она повторяется?
 - как посылать inner-HTMLli в другую вкладку?

**Comment by coursar** [comment]
1. Произвольные

**Comment by DamirZaripov16** [comment]
@coursar Ильназ, не совсем понял второй ответ. Можно ли сделать с if нечто подобное, но только с повторяющейся ссылкой? Например:
 `if (this.value.match(/^[ ]+$/)) {
        this.value = ''
}`

И еще по 3 ответу. Мы же еще не разобрали как делать табы внутри приложения? Можно ли воспользоваться данной статьей для построения табов как правильной? [https://webdesign.tutsplus.com/ru/tutorials/how-to-build-a-responsive-tab-component-with-css-and-a-touch-of-javascript--cms-30456](url)

**Comment by coursar** [comment]
2. Почему просто на if не проверить, есть ли такая ссылка или нет? Либо я не понял вопрос.
3. Переставляете css-класс, у которого display: none, display: block

**Comment by DamirZaripov16** [comment]
`if (ev.target.contains(${this.link})) {
        ev.preventDefault();`
Примерно таким образом запретить повторяющуюся ссылку?

**Comment by coursar** [comment]
Нет, зачем, ссылки у вас где-то хранятся в массиве. Вы проверяете, есть ли в массиве объект с такой ссылкой - если есть, то не добавляете

**Comment by DamirZaripov16** [comment]
Т.е. нужно в lib.js создать переменную, где в массиве будет храниться this.link и в app.js через if проверить совпадение ссылок? Подскажите, пожалуйста, синтаксис для написания этой операции.

**Comment by coursar** [comment]
зачем?

хранилище и класс для ссылки
```javascript
export class Link {
    constructor(url, tags) {
       this.url = url;
       this.tags = tags;
       this.done = false;
    }
}

export class LinkStorage {
    constructor() {
        this.links = []
    }

   add(link) {
       if (this.links.some(el => el.url === link.url)) {
           // TODO: такая ссылка уже есть в массиве
           return;
       }
       this.links.push(link);
   }
}
```

Вместо `this.links.some()` можно использовать обычный цикл `for-of`:
```javascript
add(link) {
    for (const el of this.links) {
       if (el.url === link.url) {
          // TODO: такая ссылка уже есть в списке, нужно вернуть ошибку, например throw new Error('message');
          return;
       }
    }
}
```
