### ISSUE TITLE
Теги

### ISSUE THREAD

**Issue by DamirZaripov16** [DamirZaripov16/readLater#3]
@coursar Ильназ, как лучше поменять все пробелы в тегах на "_" : через `${item.tag}.replace(//g, "_")`  или `${item.tag}.split("").join("_")` ?
И можно ли убрать инпут с тегами, если ввод тегов можно реализовать через инпут с именем? 
К примеру: https://github.com/DamirZaripov16/readLater/blob/08657dc5e3082048a0773319fd48501a075c8e80/src/app/readLater.js#L54-L59

**Comment by coursar** [comment]
1. Логичнее через replace
2. Конечно
