### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by DamirZaripov16** [DamirZaripov16/readLater#4]
@coursar Ильназ, TravisCI все так же не пускает билд, теперь и через Heroku. Сделал все так, как у Вас в видео. В чем возникла проблема?

**Comment by coursar** [comment]
Во-первых, текущий бейджик у вас вообще указывает на `gas`, а не на `readLater`.

Во-вторых, читайте, что вам пишут в логе:
```
Message: Couldn't find that app.
Reference: 
failed to deploy
```

Вы точно на heroku создали приложение, которое называется readLater? Приложите скриншот, где это указано.

**Comment by DamirZaripov16** [comment]
@coursar Поменял на настоящее и, Трэвис пустил, но Хероку говорит, что кода нет
![default](https://user-images.githubusercontent.com/45975858/53442488-7354aa80-3a1a-11e9-8a3b-86eb16bf096f.png)
![2](https://user-images.githubusercontent.com/45975858/53442489-7354aa80-3a1a-11e9-91c6-5387a7c31069.png)

**Comment by coursar** [comment]
так вам надо "/items" а не просто "/"
